### POST Request to register server
POST http://localhost:3000/registration
Accept: application/json
Content-Type: application/json

{
  "guildId": "850840267082563596",
  "guildName": "test",
  "authorizedDegenRoleId": "sdfdsfs",
  "categoryChannelId": "",
  "privateChannelId": "",
  "announcementChannelId": ""
}

### DELETE Request to delete server
DELETE http://localhost:3000/registration/850840267082563596
Accept: application/json
Content-Type: application/json
