import { ApiProperty } from '@nestjs/swagger';
import { EventType } from '../../enums/event-type.enum';

export default class PostEventResponseDto {
  @ApiProperty({
    required: true,
    description: 'The ID of the event (generated by the server)',
  })
  _id: string;

  @ApiProperty({
    required: true,
    description: 'The start date of the event',
  })
  startDate: Date;

  @ApiProperty({
    required: true,
    description: 'The end date of the event',
  })
  endDate: Date;

  @ApiProperty({
    required: true,
    description: 'The enum type of the event',
  })
  eventType: EventType;
}
