name: badge-buddy-api
services:
  badge_buddy_api_local:
    container_name: badge_buddy_api_local
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    networks:
      - local_server
    profiles:
      - local

  badge_buddy_api_qa:
    container_name: badge_buddy_api_qa
    image: amaredeus/badge-buddy-api:latest-qa
    env_file:
      - .env.staging
    networks:
      - qa_server
    profiles:
      - qa

  badge_buddy_api_prod:
    container_name: badge_buddy_api_prod
    image: amaredeus/badge-buddy-api:latest
    env_file:
      - .env.production
    networks:
      - prod_server
      - elastic
    profiles:
      - prod

networks:
  local_server:
    external: true
  qa_server:
    external: true
  prod_server:
    external: true
