name: local_badge-buddy
services:
  api-1:
    container_name: api-1_local-badge-buddy
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      tags:
        - solidchain/badge-buddy-api:dev
    env_file:
      - .env
    environment:
      MARIADB_HOST: local_badge-buddy-mariadb-1
      MARIADB_PASSWORD: local-pass
      REDIS_HOST: local_badge-buddy-redis-1
    networks:
      - local_server
    ports:
      - 3011:3000
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    networks:
      - local_server

  mariadb:
    image: mariadb:latest
    networks:
      - local_server
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: local-pass
      MARIADB_DATABASE: badgebuddy
    volumes:
      - ../../packages/common/src/common-typeorm/scripts/mysql.setup.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  local_server:
    external: true
