name: prod_badge-buddy-api
services:

  api:
    image: solidchain/badge-buddy-api:latest
    restart: always
    ports:
      - 3002:3000
    networks:
      - prod_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  prod_server:
    external: true
