name: local_badgebuddy
services:
  api-1:
    container_name: api-1_local-badgebuddy
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      tags:
        - badgebuddy/api:dev
    env_file:
      - .env
    environment:
      MARIADB_HOST: local_badgebuddy-mariadb-1
      MARIADB_PASSWORD: local-pass
      REDIS_HOST: local_badgebuddy-redis-1
    networks:
      - local_server
    ports:
      - 3011:3000
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    networks:
      - local_server
    ports:
      - 6379:6379

  mariadb:
    image: mariadb:10.11-jammy
    networks:
      - local_server
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: local-pass
      MARIADB_DATABASE: badgebuddy
    volumes:
      - ../../packages/common/src/common-typeorm/scripts/mysql.setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

networks:
  local_server:
    external: true
