name: local_badge-buddy-api
services:

  api:
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      tags:
        - solidchain/badge-buddy-api:dev
    env_file:
      - .env
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PASSWORD: local-pass
      REDIS_HOST: redis
    networks:
      - local_server
    ports:
      - 3011:3000
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    networks:
      - local_server

  mariadb:
    image: mariadb:latest
    networks:
      - local_server
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: local-pass
      MARIADB_DATABASE: badge_buddy
    volumes:
      - ../../packages/common/src/common-typeorm/scripts/mysql.setup.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  local_server:
    external: true
