name: badge-buddy-api
services:
  badge_buddy_api_local:
    container_name: badge_buddy_api_local
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    networks:
      - local_server
    ports:
      - 3002:3000
    profiles:
      - local

  badge_buddy_api_qa:
    container_name: badge_buddy_api_qa
    image: amaredeus/badge-buddy-api:latest-beta
    ports:
      - 3010:3000
    networks:
      - qa_server
      - elastic
    profiles:
      - staging
    environment:
      DOTENV_KEY: ${DOTENV_KEY}

  badge_buddy_api_prod:
    container_name: badge_buddy_api_prod
    image: amaredeus/badge-buddy-api:latest
    ports:
      - 3002:3000
    networks:
      - prod_server
      - elastic
    profiles:
      - production
    environment:
      DOTENV_KEY: ${DOTENV_KEY}

networks:
  local_server:
    external: true
  qa_server:
    external: true
  prod_server:
    external: true
  elastic:
    external: true
