name: stage_badgebuddy
services:
  api-1:
    container_name: api-1_stage-badgebuddy
    image: amaredeus/api:next
    restart: always
    ports:
      - 3010:3000
    networks:
      - stage_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  stage_server:
    external: true
