name: badge-buddy-api
services:
  badge_buddy_api_local:
    container_name: badge_buddy_api_local
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    networks:
      - local_server
    ports:
      - 3002:3000
    profiles:
      - local
    volumes:
      - ./logs:/app/logs

  redis_local:
    container_name: redis_local
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - local_server
    profiles:
      - local

  badge_buddy_api_qa:
    container_name: badge_buddy_api_qa
    image: amaredeus/badge-buddy-api:latest-beta
    restart: always
    ports:
      - 3010:3000
    networks:
      - qa_server
    profiles:
      - staging
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
      NODE_ENV: 'staging'
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

  badge_buddy_api_prod:
    container_name: badge_buddy_api_prod
    image: amaredeus/badge-buddy-api:latest
    restart: always
    ports:
      - 3002:3000
    networks:
      - prod_server
    profiles:
      - production
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
      NODE_ENV: 'production'
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  local_server:
    external: true
  qa_server:
    external: true
  prod_server:
    external: true
  elastic:
    external: true
