### POST Request to register guild
POST http://localhost:3000/events/850840267082563596
Accept: application/json
Content-Type: application/json

{
  "name": "POAP Event Test Name",
  "organizerId": "",
  "channelId": "",
  "duration": 0
}

### GET Request to get guild
GET http://localhost:3000/guilds/850840267082563596

### DELETE Request to delete guild
DELETE http://localhost:3000/guilds/850840267082563596
Accept: application/json
Content-Type: application/json


POST /events/:guildId (start)
PUT /events/:guildId (stop
POST /events/distribution/:guildId (disburse manually)
POST /events/schedule/:guildId (start in future)
PUT /events/schedule/:guildId (stop in future)

GET /events/:guildId (all events)
GET /events/:guildId?organizerId= (all events by organizer)
GET /events/:guildId?channelId= (all events by channel)
GET /events/:guildId?organizerId=&channelId= (all events by organizer and channel)
GET /events/:guildId?fromDate= (all events from date)
GET /events/:guildId?toDate= (all events to date)
GET /events/:guildId?fromDate=&toDate= (all events from date to date)
