export const ENV_AUTH_ALLOWED_CLIENT_IDS = 'AUTH_ALLOWED_CLIENT_IDS' as const;
export const ENV_AUTH_SECRET_ENCRYPT_KEY = 'AUTH_SECRET_ENCRYPT_KEY' as const;
export const ENV_AUTH_ISSUER = 'AUTH_ISSUER' as const;

export const ENV_AUTH_PROCESSOR_CLIENT_ID = 'AUTH_PROCESSOR_CLIENT_ID' as const;
export const ENV_AUTH_PROCESSOR_CLIENT_SECRET = 'AUTH_PROCESSOR_CLIENT_SECRET' as const;

export const ENV_AUTH_DISCORD_BOT_CLIENT_ID = 'AUTH_DISCORD_BOT_CLIENT_ID' as const;
export const ENV_AUTH_DISCORD_BOT_CLIENT_SECRET = 'AUTH_DISCORD_BOT_CLIENT_SECRET' as const;