export const AUTH_ALLOWED_CLIENT_IDS_ENV = 'AUTH_ALLOWED_CLIENT_IDS' as const;
export const AUTH_SECRET_ENCRYPT_KEY_ENV = 'AUTH_SECRET_ENCRYPT_KEY' as const;
export const AUTH_ISSUER_ENV = 'AUTH_ISSUER' as const;
export const AUTH_PROCESSOR_CLIENT_ID_ENV = 'AUTH_PROCESSOR_CLIENT_ID' as const;
export const AUTH_PROCESSOR_CLIENT_SECRET_ENV = 'AUTH_PROCESSOR_CLIENT_SECRET' as const;
export const AUTH_GOOGLE_CLIENT_ID_ENV = 'AUTH_GOOGLE_CLIENT_ID' as const;
export const AUTH_GOOGLE_CLIENT_SECRET_ENV = 'AUTH_GOOGLE_CLIENT_SECRET' as const;
export const AUTH_GOOGLE_REDIRECT_URI_ENV = 'AUTH_GOOGLE_REDIRECT_URI' as const;
export const AUTH_DISCORD_BOT_CLIENT_ID_ENV = 'AUTH_DISCORD_BOT_CLIENT_ID' as const;
export const AUTH_DISCORD_BOT_CLIENT_SECRET_ENV = 'AUTH_DISCORD_BOT_CLIENT_SECRET' as const;
export const AUTH_ENABLED = 'AUTH_ENABLED' as const;

export const DISCORD_BOT_TOKEN_ENV = 'DISCORD_BOT_TOKEN' as const;
export const DISCORD_BOT_APPLICATION_ID_ENV = 'DISCORD_BOT_APPLICATION_ID' as const;
export const DISCORD_BOT_PUBLIC_KEY_ENV = 'DISCORD_BOT_PUBLIC_KEY' as const;
export const DISCORD_CLIENT_SECRET_ENV = 'DISCORD_CLIENT_SECRET' as const;
export const DISCORD_OWNER_ID_ENV = 'DISCORD_OWNER_ID' as const;
export const DISCORD_REDIRECT_URI_ENV = 'DISCORD_REDIRECT_URI' as const;
