#file: noinspection YAMLSchemaValidation
name: Create PR for dev
on:
  push:
    branches:
      - dev
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: solidchain/badge-buddy-api:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: gh pr close dev | exit 0
      - run: gh pr create --base release/dev --fill --title "deploy dev -> release/dev" | exit 0
