#file: noinspection YAMLSchemaValidation
name: Create PR for dev
on:
  push:
    branches:
      - dev
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    outputs:
      pnpm: ${{ steps.pnpm-version.outputs.prop }}
      package: ${{ steps.package-version.outputs.prop }}
      node: ${{ steps.node-version.outputs.prop }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - name: Retrieve node version
        id: node-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.node'
      - name: Retrieve pnpm version
        id: pnpm-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.pnpm'
      - name: Retrieve package version
        id: package-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
  build-deploy-docker:
    needs:
      - build-and-test
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:next
            ${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:${{ needs.build-and-test.outputs.package }}
          build-args: |
            NODE_VERSION=${{ needs.build-and-test.outputs.node }}
            PNPM_VERSION=${{ needs.build-and-test.outputs.pnpm }}
  deploy-qa:
    needs:
      - build-deploy-docker
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Transfer compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "compose.yml"
          target: "${{ secrets.APP_PATH_STAGING }}"
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOTENV_KEY: "${{ secrets.DOTENV_KEY_STAGING }}"
          NODE_VERSION: "${{ needs.build-and-test.outputs.node }}"
          PNPM_VERSION: "${{ needs.build-and-test.outputs.pnpm }}"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOTENV_KEY,NODE_VERSION,PNPM_VERSION
          script: |
            cd ${{ secrets.APP_PATH_STAGING }}
            docker compose --profile staging pull
            docker compose --profile staging stop
            docker compose --profile staging up --build -d
  create-pr:
    needs: deploy-qa
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch
      - run: git pull --tags
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: gh pr close dev | exit 0
      - run: gh pr create --base release/dev --fill --title "deploy dev -> release/dev" | exit 0
