#file: noinspection YAMLSchemaValidation
name: Deploy Staging
on:
  push:
    branches:
      - release/dev
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: pnpm dlx standard-version --prerelease
      - name: Retrieve package version
        id: package-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: |
            solidchain/badge-buddy-api:next
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            solidchain/badge-buddy-api:next
            solidchain/badge-buddy-api:${{ steps.package-version.outputs.prop }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Transfer compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "compose.yml"
          target: "${{ secrets.APP_PATH_STAGING }}"
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY_STAGING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOTENV_KEY
          script: |
            cd ${{ secrets.APP_PATH_STAGING }}
            docker compose --profile staging pull
            docker compose --profile staging stop
            DOTENV_KEY=$DOTENV_KEY docker compose --profile staging up -d
      - run: git push --follow-tags
      - run: gh pr close release/dev | exit 0
      - run: gh pr create --base main --fill --title "deploy v${{ steps.package-version.outputs.prop }} to production"
      - run: git checkout dev
      - run: git merge --no-ff release/dev -m "sync branch release/dev v${{ steps.package-version.outputs.prop }} into dev" | exit 0
      - run: git push
