name: Publish Docker image
on:
    push:
        branches:
        - dev
jobs:
    publish:
        environment: staging
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Configure environment variables
          run: |
            echo "NODE_ENV=staging" >> $GITHUB_ENV
            echo "PROJECT_VERSION=1.0.0-beta" >> $GITHUB_ENV
            echo "NODE_VERSION=20.3.1" >> $GITHUB_ENV
            echo "PNPM_VERSION=8.6.10" >> $GITHUB_ENV
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            build-args: |
              PNPM_VERSION=${{ env.PNPM_VERSION }}
              NODE_VERSION=${{ env.NODE_VERSION }}
            tags: ${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:latest-staging,${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:${{ env.PROJECT_VERSION }}
