name: Publish Docker image
on:
    push:
        branches:
        - dev
jobs:
    publish-qa:
        environment: staging
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Retrieve Package Version
          id: package-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'version'
        - name: Retrieve Node Version
          id: node-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.node'
        - name: Retrieve PNPM Version
          id: pnpm-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.pnpm'
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            build-args: |
              PNPM_VERSION=${{ steps.pnpm-version.outputs.prop }}
              NODE_VERSION=${{ steps.node-version.outputs.prop }}
            tags: "${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:latest-beta,${{ secrets.DOCKER_USERNAME 
            }}/badge-buddy-api:${{ steps.package-version.outputs.prop }}"
