#file: noinspection YAMLSchemaValidation
name: Publish Docker image
on:
    push:
        branches:
        - dev
jobs:
    publish-qa:
        environment: staging
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Retrieve Package Version
          id: package-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'version'
        - name: Retrieve Node Version
          id: node-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.node'
        - name: Retrieve PNPM Version
          id: pnpm-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.pnpm'
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            build-args: |
              PNPM_VERSION=${{ steps.pnpm-version.outputs.prop }}
              NODE_VERSION=${{ steps.node-version.outputs.prop }}
            tags: "${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:latest-beta,${{ secrets.DOCKER_USERNAME 
            }}/badge-buddy-api:${{ steps.package-version.outputs.prop }}"
        - name: Deploy to staging
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/badge-buddy-api:latest-beta
              docker stop badge-buddy-api
              docker rm badge-buddy-api
              cd ${{ secrets.APP_PATH }}
              curl -H 'Authorization: token ${{ secrets.GH_TOKEN }}' \
                -H 'Accept: application/vnd.github.v3.raw' \
                -o 'package.json' \
                -L 'https://api.github.com/repos/SlinkyPotato/badge-buddy-api/contents/package.json?ref=dev'
              curl -H 'Authorization: ${{ secrets.GH_TOKEN }}' \
                -H 'Accept: application/vnd.github.v3.raw' \
                -o 'compose.yml' \
                -L 'https://api.github.com/repos/SlinkyPotato/badge-buddy-api/contents/compose.yml?ref=dev'
              DOTENV_KEY=${{ secrets.DOTENV_STAGING }} docker compose --profile staging up --build -d
